//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursachMain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kursachEntities : DbContext
    {
        public kursachEntities()
            : base("name=kursachEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Виды_практики> Виды_практики { get; set; }
        public virtual DbSet<Группы> Группы { get; set; }
        public virtual DbSet<Договоры> Договоры { get; set; }
        public virtual DbSet<ПланНабора> ПланНабора { get; set; }
        public virtual DbSet<Предприятия> Предприятия { get; set; }
        public virtual DbSet<Преподаватели> Преподаватели { get; set; }
        public virtual DbSet<ПроведениеПрактики> ПроведениеПрактики { get; set; }
        public virtual DbSet<Специальности> Специальности { get; set; }
        public virtual DbSet<Студенты> Студенты { get; set; }
        public virtual DbSet<Текущая_практика> Текущая_практика { get; set; }
    }
}
